In [1]:
import pandas as pd

In [2]:
df1 = pd.read_excel("/Users/romitbenkar/Downloads/Master_FSC_Sheet_ABC&Sarvodaya New.xlsx")
df1

,Industry,Sector,Function,WiZR Skills,Concepts,Concept Description,PRODUCTION Function ID,PRODUCTION Skill ID,PRODUCTION Concept ID,Core/Elective,Company,Beginner,Intermediate,Advanced,PID
0,Banking & Capital Markets,Insurance Advisory & Broking,Finance & Accounts,Accounting & Auditing,Audit Report Preparation,Competence in preparing clear and comprehensiv...,37,18,5281,Core,Aditya Birla Money Insurance Advisory Services...,256,144,112,"5576,5576,5576,5576,5576,5576,5576,5576,6680,6..."
1,Banking & Capital Markets,Insurance Advisory & Broking,Finance & Accounts,Accounting & Auditing,Audit Risk Assessment,Expertise in identifying and evaluating risks ...,37,18,5162,Core,Aditya Birla Money Insurance Advisory Services...,216,120,112,"4660,4660,4660,4660,4660,4660,4660,4660,5576,5..."
2,Banking & Capital Markets,Insurance Advisory & Broking,Finance & Accounts,Accounting & Auditing,Compliance Auditing,Ability to conduct audits that assess complian...,37,18,5090,Core,Aditya Birla Money Insurance Advisory Services...,104,68,44,"5576,5576,5576,5576,5998,5998,5998,5998,6680,6..."
3,Banking & Capital Markets,Insurance Advisory & Broking,Finance & Accounts,Accounting & Auditing,Continuous Auditing Practices,Familiarity with continuous auditing methods t...,37,18,5534,Core,Aditya Birla Money Insurance Advisory Services...,216,112,80,"4660,4660,4660,4660,4660,4660,4660,4660,6680,6..."
4,Banking & Capital Markets,Insurance Advisory & Broking,Finance & Accounts,Accounting & Auditing,Data Analysis for Auditing,Skills in using data analytical tools to enhan...,37,18,5378,Core,Aditya Birla Money Insurance Advisory Services...,616,232,168,"4660,4660,4660,4660,4660,4660,4660,4660,6314,6..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47182,Banking & Capital Markets,Asset Management (Stressed Assets),Analytics,ML Ops,Model Deployment,Strategies for reliable and easy deployment of...,24,319,6878,Core,Aditya Birla Stressed Asset AMC Private Limited,66,12,30,"6829,6829,6829,7059,7059,7059,7543,7543,7543,8..."
47183,Banking & Capital Markets,Asset Management (Stressed Assets),Analytics,ML Ops,Model Development and Training,Techniques for designing and training ML model...,24,319,6877,Core,Aditya Birla Stressed Asset AMC Private Limited,30,9,9,"6829,6829,6829,10000,10000,10000,29836,29836,2..."
47184,Banking & Capital Markets,Asset Management (Stressed Assets),Analytics,ML Ops,Monitoring and Maintenance,Tools and techniques for monitoring performanc...,24,319,6881,Core,Aditya Birla Stressed Asset AMC Private Limited,12,3,9,"7151,7151,7151,9478,9478,9478,25323,25323,2532..."
47185,Banking & Capital Markets,Asset Management (Stressed Assets),Analytics,ML Ops,Security and Compliance,"Ensure system and data security, adhering to r...",24,319,6882,Core,Aditya Birla Stressed Asset AMC Private Limited,87,21,9,"7151,7151,7151,9478,9478,9478,25323,25323,2532..."
47186,Banking & Capital Markets,Asset Management (Stressed Assets),Analytics,Personal Development,Personal Finance,Understanding and managing one`s finances effe...,24,130,4577,Elective,Aditya Birla Stressed Asset AMC Private Limited,1147,407,333,"5661,5661,5661,5661,5661,5661,5661,5661,5661,5..."

In [31]:
# df1= pd.read_excel("/Users/romitbenkar/Desktop/Office/19-12-24/productSkillConceptDataRecords_WithINR.xlsx")
# df1

,product_sfid,product_id,course_journey__c,product_name,course_level,skill_id,concepts,CPP name,INR
0,01t8n000000GrJPAA0,4641,B2B,PG Program in Digital Marketing Strategies (PG...,Advanced,117,5648,Amity Future Academy,170000.0
1,01t8n000000GrJQAA0,4642,B2B,PG Program in Product Management (PGP-PM),Advanced,36,5336,Amity Future Academy,215000.0
2,01t8n000000GrJRAA0,4643,B2B,Post Graduate Diploma in Management,Advanced,37,4590,Amity Future Academy,120000.0
3,01t8n000000GrJSAA0,4644,B2B,Post Graduate Diploma in Management,Advanced,37,4590,Amity Future Academy,120000.0
4,01t8n000000GrJTAA0,4645,B2B,Post Graduate Program in Big Data Architecture...,Advanced,64,"4906 , 4928",Amity Future Academy,100000.0
...,...,...,...,...,...,...,...,...,...
19466,przza8505u,20687,B2B,Professional Certification In Human Resource M...,Beginner,94,NaN,MITSDE,6165000.0
19467,przzd0g0p1,28069,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,44,5005,Udemy,0.0
19468,przzj4igrr,14130,B2B,Resourcing a Project Schedule,Beginner,39,6101,Coursera,0.0
19469,przzvn6z59,14710,B2B,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,104,6501,Coursera,0.0
19470,przzxluxi8,20241,B2B,Generative AI Primer,Beginner,130,6388,Coursera,0.0

In [3]:
df1

# Replace 'Data' with the actual column name you want to process
column_to_split = "PID"  # Replace with the name of your column

# Initialize a new DataFrame to store the results
processed_data = pd.DataFrame()

try:
    # Process the data from bottom to top
    for index in reversed(df1.index):
        # Get the current cell value
        cell_value = df1.at[index, column_to_split]

        if pd.isna(cell_value) or cell_value == "":
            # If the cell is empty, add it as is
            processed_data = pd.concat([processed_data, df1.iloc[[index]]])
        else:
            # Split the cell value into a list if it contains data
            split_values = str(cell_value).split(",")  # Update delimiter if needed
            for value in split_values:
                # Append each split value as a new row, duplicating other columns
                row = df1.iloc[[index]].copy()
                row[column_to_split] = value.strip()  # Remove extra spaces
                processed_data = pd.concat([processed_data, row])
except Exception as e:
    print(f"An error occurred: {e}")

# Reverse the processed DataFrame to maintain the original order
processed_data = processed_data.iloc[::-1]

# Save the result to a new Excel file
output_file = "/Users/romitbenkar/Downloads/Split_data.xlsx"
processed_data.to_excel(output_file, index=False)

print(f"Data has been processed and saved to {output_file}")

KeyboardInterrupt:

In [33]:
processed_data

,product_sfid,product_id,course_journey__c,product_name,course_level,skill_id,concepts,CPP name,INR
0,01t8n000000GrJPAA0,4641,B2B,PG Program in Digital Marketing Strategies (PG...,Advanced,117,5648,Amity Future Academy,170000.0
1,01t8n000000GrJQAA0,4642,B2B,PG Program in Product Management (PGP-PM),Advanced,36,5336,Amity Future Academy,215000.0
2,01t8n000000GrJRAA0,4643,B2B,Post Graduate Diploma in Management,Advanced,37,4590,Amity Future Academy,120000.0
3,01t8n000000GrJSAA0,4644,B2B,Post Graduate Diploma in Management,Advanced,37,4590,Amity Future Academy,120000.0
4,01t8n000000GrJTAA0,4645,B2B,Post Graduate Program in Big Data Architecture...,Advanced,64,4928,Amity Future Academy,100000.0
...,...,...,...,...,...,...,...,...,...
19466,przza8505u,20687,B2B,Professional Certification In Human Resource M...,Beginner,94,NaN,MITSDE,6165000.0
19467,przzd0g0p1,28069,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,44,5005,Udemy,0.0
19468,przzj4igrr,14130,B2B,Resourcing a Project Schedule,Beginner,39,6101,Coursera,0.0
19469,przzvn6z59,14710,B2B,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,104,6501,Coursera,0.0
19470,przzxluxi8,20241,B2B,Generative AI Primer,Beginner,130,6388,Coursera,0.0

In [34]:
# Rename specific columns
df = df.rename(columns={'Skill IDs': 'skill_id', 'Concept IDs': 'concepts'})

In [36]:
df["concat"]=df["skill_id"].astype(str)+"|"+df["concepts"].astype(str)
df

,Function,Function IDs,WiZR Skills,skill_id,Core/Elective,Concepts,concepts,Concept Description,concat
0,Analytics,24,Data Visualization,67,Core,Visualization Design Principles,5765,Expertise in applying design principles to cre...,67|5765
1,Analytics,24,Data Visualization,67,Core,Tool Proficiency,5056,Skills in utilizing data visualization tools s...,67|5056
2,Analytics,24,Data Visualization,67,Core,Data Interpretation,5136,Proficiency in interpreting complex data sets ...,67|5136
3,Analytics,24,Data Visualization,67,Core,Interactive Visualizations,5455,Competence in creating interactive visualizati...,67|5455
4,Analytics,24,Data Visualization,67,Core,Dashboard Development,5206,Ability to design and develop informative dash...,67|5206
...,...,...,...,...,...,...,...,...,...
2601,Audit,34,Personal Development,130,Elective,Personal Branding and Image Management,5812,Crafting a compelling personal brand and manag...,130|5812
2602,Audit,34,Personal Development,130,Elective,Stress Management (Personal Development),6063,Implementing techniques and strategies to cope...,130|6063
2603,Audit,34,Personal Development,130,Elective,Mindset and Motivation (Personal Development),6118,Cultivating a growth mindset and sustaining mo...,130|6118
2604,Audit,34,Personal Development,130,Elective,Health and Well-being (Personal Development),6061,Prioritizing physical and mental health throug...,130|6061
2605,Audit,34,Personal Development,130,Elective,"Critical Thinking, Problem Solving - Personal",6388,Developing the ability to analyze information ...,130|6388

In [37]:
#concat
processed_data["concat"] = processed_data["skill_id"].astype(str) + "|" + processed_data["concepts"].astype(str)
processed_data

,product_sfid,product_id,course_journey__c,product_name,course_level,skill_id,concepts,CPP name,INR,concat
0,01t8n000000GrJPAA0,4641,B2B,PG Program in Digital Marketing Strategies (PG...,Advanced,117,5648,Amity Future Academy,170000.0,117|5648
1,01t8n000000GrJQAA0,4642,B2B,PG Program in Product Management (PGP-PM),Advanced,36,5336,Amity Future Academy,215000.0,36|5336
2,01t8n000000GrJRAA0,4643,B2B,Post Graduate Diploma in Management,Advanced,37,4590,Amity Future Academy,120000.0,37|4590
3,01t8n000000GrJSAA0,4644,B2B,Post Graduate Diploma in Management,Advanced,37,4590,Amity Future Academy,120000.0,37|4590
4,01t8n000000GrJTAA0,4645,B2B,Post Graduate Program in Big Data Architecture...,Advanced,64,4928,Amity Future Academy,100000.0,64|4928
...,...,...,...,...,...,...,...,...,...,...
19466,przza8505u,20687,B2B,Professional Certification In Human Resource M...,Beginner,94,NaN,MITSDE,6165000.0,94|nan
19467,przzd0g0p1,28069,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,44,5005,Udemy,0.0,44|5005
19468,przzj4igrr,14130,B2B,Resourcing a Project Schedule,Beginner,39,6101,Coursera,0.0,39|6101
19469,przzvn6z59,14710,B2B,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,104,6501,Coursera,0.0,104|6501
19470,przzxluxi8,20241,B2B,Generative AI Primer,Beginner,130,6388,Coursera,0.0,130|6388

In [38]:
merged_file = pd.merge(processed_data,df, how ="left", on="concat",)
merged_file

,product_sfid,product_id,course_journey__c,product_name,course_level,skill_id_x,concepts_x,CPP name,INR,concat,Function,Function IDs,WiZR Skills,skill_id_y,Core/Elective,Concepts,concepts_y,Concept Description
0,01t8n000000GrJPAA0,4641,B2B,PG Program in Digital Marketing Strategies (PG...,Advanced,117,5648,Amity Future Academy,170000.0,117|5648,Digital Transformation,32.0,Content Marketing,117.0,Elective,SEO (Search Engine Optimization),5648.0,Competence in optimizing content with relevant...
1,01t8n000000GrJPAA0,4641,B2B,PG Program in Digital Marketing Strategies (PG...,Advanced,117,5648,Amity Future Academy,170000.0,117|5648,Marketing,39.0,Content Marketing,117.0,Core,SEO (Search Engine Optimization),5648.0,Competence in optimizing content with relevant...
2,01t8n000000GrJQAA0,4642,B2B,PG Program in Product Management (PGP-PM),Advanced,36,5336,Amity Future Academy,215000.0,36|5336,Digital Transformation,32.0,Product Management,36.0,Core,Agile Product Development,5336.0,Knowledge of agile methodologies to manage pro...
3,01t8n000000GrJQAA0,4642,B2B,PG Program in Product Management (PGP-PM),Advanced,36,5336,Amity Future Academy,215000.0,36|5336,Product,33.0,Product Management,36.0,Core,Agile Product Development,5336.0,Knowledge of agile methodologies to manage pro...
4,01t8n000000GrJRAA0,4643,B2B,Post Graduate Diploma in Management,Advanced,37,4590,Amity Future Academy,120000.0,37|4590,Digital Transformation,32.0,Business Management,37.0,Core,Project Management,4590.0,Ability to oversee digital projects from conce...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75747,przzxluxi8,20241,B2B,Generative AI Primer,Beginner,130,6388,Coursera,0.0,130|6388,Customer Service,31.0,Personal Development,130.0,Elective,"Critical Thinking, Problem Solving - Personal",6388.0,Developing the ability to analyze information ...
75748,przzxluxi8,20241,B2B,Generative AI Primer,Beginner,130,6388,Coursera,0.0,130|6388,Distribution,25.0,Personal Development,130.0,Elective,"Critical Thinking, Problem Solving - Personal",6388.0,Developing the ability to analyze information ...
75749,przzxluxi8,20241,B2B,Generative AI Primer,Beginner,130,6388,Coursera,0.0,130|6388,Compliance,28.0,Personal Development,130.0,Elective,"Critical Thinking, Problem Solving - Personal",6388.0,Developing the ability to analyze information ...
75750,przzxluxi8,20241,B2B,Generative AI Primer,Beginner,130,6388,Coursera,0.0,130|6388,Sales,29.0,Personal Development,130.0,Elective,"Critical Thinking, Problem Solving - Personal",6388.0,Developing the ability to analyze information ...
75751,przzxluxi8,20241,B2B,Generative AI Primer,Beginner,130,6388,Coursera,0.0,130|6388,Audit,34.0,Personal Development,130.0,Elective,"Critical Thinking, Problem Solving - Personal",6388.0,Developing the ability to analyze information ...

In [39]:
merged_file.to_excel("/Users/romitbenkar/Desktop/Office/19-12-24/final_output.xlsx")